# Generated by Django 4.2.9 on 2024-03-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatc_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
