# Generated by Django 4.2.9 on 2024-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='avilable_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='avilable_time',
            field=models.ManyToManyField(to='doctor.avilabletime'),
        ),
    ]
